name: dbt-ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dbt:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      DBT_PROFILES_DIR: .

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_CI_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Create profiles.yml
        run: |
          cat > profiles.yml <<EOF
          olist_batch:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: oauth
                project: project-de-492612
                dataset: analytics_ci
                location: EU
                threads: 4
          EOF

      - name: dbt deps
        run: dbt deps

      - name: dbt build
        run: dbt build --target ci